// Code generated by cmd/cgo; DO NOT EDIT.

package gtk

import "unsafe"

import _ "runtime/cgo"

import "syscall"

var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
func _cgoCheckPointer(interface{}, interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
func _cgoCheckResult(interface{})

//go:cgo_import_static _cgo_ca85fdcde0bd_Cfunc_create_tray_icon
//go:linkname __cgofn__cgo_ca85fdcde0bd_Cfunc_create_tray_icon _cgo_ca85fdcde0bd_Cfunc_create_tray_icon
var __cgofn__cgo_ca85fdcde0bd_Cfunc_create_tray_icon byte
var _cgo_ca85fdcde0bd_Cfunc_create_tray_icon = unsafe.Pointer(&__cgofn__cgo_ca85fdcde0bd_Cfunc_create_tray_icon)

//go:cgo_unsafe_args
func _Cfunc_create_tray_icon() (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_ca85fdcde0bd_Cfunc_create_tray_icon, uintptr(unsafe.Pointer(&r1)))
	if _Cgo_always_false {
	}
	return
}
