// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/mc/go/pkg/mod/guitest/goey@v0.8.0/internal/gtk/mc.go:1:1
package gtk

/*
#include "mc.h"
*/
import _ "unsafe"

func CreateTray() {
	// #cgo linux pkg-config: gtk+-3.0
	( /*line :10:2*/_Cfunc_create_tray_icon /*line :10:19*/)()
}
