/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: thunks.i */

#define SWIGMODULE gtk
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


    #include "thunks.h"

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_gtk_0b05487f82a429b0(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_widgetClose_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  widgetClose(arg1);
  
}


bool _wrap_widgetCanFocus_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (bool)widgetCanFocus(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_widgetGrabFocus_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  widgetGrabFocus(arg1);
  
}


bool _wrap_widgetIsFocus_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (bool)widgetIsFocus(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_widgetSendKey_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1, bool _swig_go_2) {
  void *arg1 = (void *) 0 ;
  unsigned int arg2 ;
  bool arg3 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  arg3 = (bool)_swig_go_2; 
  
  widgetSendKey(arg1,arg2,arg3);
  
}


intgo _wrap_widgetMinHeight_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (int)widgetMinHeight(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_widgetMinHeightForWidth_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)widgetMinHeightForWidth(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_widgetNaturalHeight_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (int)widgetNaturalHeight(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_widgetNaturalHeightForWidth_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)widgetNaturalHeightForWidth(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_widgetMinWidth_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (int)widgetMinWidth(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_widgetNaturalWidth_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (int)widgetNaturalWidth(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_widgetNaturalWidthForHeight_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)widgetNaturalWidthForHeight(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_widgetSetBounds_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, intgo _swig_go_4) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = (int)_swig_go_4; 
  
  widgetSetBounds(arg1,arg2,arg3,arg4,arg5);
  
}


bool _wrap_widgetSensitive_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (bool)widgetSensitive(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_widgetCanDefault_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (bool)widgetCanDefault(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_widgetSetSizeRequest_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  widgetSetSizeRequest(arg1,arg2,arg3);
  
}


void *_wrap_mountWindow_gtk_0b05487f82a429b0(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (void *)mountWindow((char const *)arg1);
  *(void **)&_swig_go_result = (void *)result; 
  free(arg1); 
  return _swig_go_result;
}


void *_wrap_windowScrolledWindow_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (void *)windowScrolledWindow(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void *_wrap_windowLayout_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (void *)windowLayout(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_windowSetLayoutSize_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  void *arg1 = (void *) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  arg3 = (unsigned int)_swig_go_2; 
  
  windowSetLayoutSize(arg1,arg2,arg3);
  
}


_gostring_ _wrap_windowTitle_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (char *)windowTitle(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_windowSetTitle_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  windowSetTitle(arg1,(char const *)arg2);
  
  free(arg2); 
}


intgo _wrap_windowVScrollbarWidth_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (unsigned int)windowVScrollbarWidth(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_windowHScrollbarHeight_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (unsigned int)windowHScrollbarHeight(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_windowShowScrollbars_gtk_0b05487f82a429b0(void *_swig_go_0, bool _swig_go_1, bool _swig_go_2) {
  void *arg1 = (void *) 0 ;
  bool arg2 ;
  bool arg3 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (bool)_swig_go_2; 
  
  windowShowScrollbars(arg1,arg2,arg3);
  
}


void _wrap_windowShow_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  windowShow(arg1);
  
}


void _wrap_windowSetDefaultSize_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  windowSetDefaultSize(arg1,arg2,arg3);
  
}


void _wrap_windowSetIcon_gtk_0b05487f82a429b0(void *_swig_go_0, char *_swig_go_1, intgo _swig_go_2, intgo _swig_go_3, intgo _swig_go_4) {
  void *arg1 = (void *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = *(unsigned char **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = (int)_swig_go_4; 
  
  windowSetIcon(arg1,(unsigned char const *)arg2,arg3,arg4,arg5);
  
}


intgo _wrap_dialogRun_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (unsigned int)dialogRun(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_dialogAddFilter_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  dialogAddFilter(arg1,(char const *)arg2,(char const *)arg3);
  
  free(arg2); 
  free(arg3); 
}


intgo _wrap_dialogResponseAccept_gtk_0b05487f82a429b0() {
  unsigned int result;
  intgo _swig_go_result;
  
  
  result = (unsigned int)dialogResponseAccept();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_dialogResponseCancel_gtk_0b05487f82a429b0() {
  unsigned int result;
  intgo _swig_go_result;
  
  
  result = (unsigned int)dialogResponseCancel();
  _swig_go_result = result; 
  return _swig_go_result;
}


void *_wrap_mountMessageDialog_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1, intgo _swig_go_2, _gostring_ _swig_go_3) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  unsigned int arg3 ;
  char *arg4 = (char *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (unsigned int)_swig_go_2; 
  
  arg4 = (char *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  
  result = (void *)mountMessageDialog(arg1,(char const *)arg2,arg3,(char const *)arg4);
  *(void **)&_swig_go_result = (void *)result; 
  free(arg2); 
  free(arg4); 
  return _swig_go_result;
}


intgo _wrap_messageDialogWithError_gtk_0b05487f82a429b0() {
  unsigned int result;
  intgo _swig_go_result;
  
  
  result = (unsigned int)messageDialogWithError();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_messageDialogWithWarn_gtk_0b05487f82a429b0() {
  unsigned int result;
  intgo _swig_go_result;
  
  
  result = (unsigned int)messageDialogWithWarn();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_messageDialogWithInfo_gtk_0b05487f82a429b0() {
  unsigned int result;
  intgo _swig_go_result;
  
  
  result = (unsigned int)messageDialogWithInfo();
  _swig_go_result = result; 
  return _swig_go_result;
}


void *_wrap_mountOpenDialog_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  result = (void *)mountOpenDialog(arg1,(char const *)arg2,(char const *)arg3);
  *(void **)&_swig_go_result = (void *)result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


void *_wrap_mountSaveDialog_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  result = (void *)mountSaveDialog(arg1,(char const *)arg2,(char const *)arg3);
  *(void **)&_swig_go_result = (void *)result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


_gostring_ _wrap_dialogGetFilename_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (char *)dialogGetFilename(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void *_wrap_mountButton_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1, bool _swig_go_2, bool _swig_go_3, bool _swig_go_4, bool _swig_go_5, bool _swig_go_6) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  bool arg4 ;
  bool arg5 ;
  bool arg6 ;
  bool arg7 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (bool)_swig_go_2; 
  arg4 = (bool)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  arg6 = (bool)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  
  result = (void *)mountButton(arg1,(char const *)arg2,arg3,arg4,arg5,arg6,arg7);
  *(void **)&_swig_go_result = (void *)result; 
  free(arg2); 
  return _swig_go_result;
}


void _wrap_buttonUpdate_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1, bool _swig_go_2, bool _swig_go_3, bool _swig_go_4, bool _swig_go_5, bool _swig_go_6) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  bool arg4 ;
  bool arg5 ;
  bool arg6 ;
  bool arg7 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (bool)_swig_go_2; 
  arg4 = (bool)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  arg6 = (bool)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  
  buttonUpdate(arg1,(char const *)arg2,arg3,arg4,arg5,arg6,arg7);
  
  free(arg2); 
}


void _wrap_buttonClick_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  buttonClick(arg1);
  
}


_gostring_ _wrap_buttonText_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (char *)buttonText(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void *_wrap_mountLabel_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (void *)mountLabel(arg1,(char const *)arg2);
  *(void **)&_swig_go_result = (void *)result; 
  free(arg2); 
  return _swig_go_result;
}


void _wrap_labelUpdate_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  labelUpdate(arg1,(char const *)arg2);
  
  free(arg2); 
}


_gostring_ _wrap_labelText_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (char *)labelText(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void *_wrap_mountCheckbox_gtk_0b05487f82a429b0(void *_swig_go_0, bool _swig_go_1, _gostring_ _swig_go_2, bool _swig_go_3, bool _swig_go_4, bool _swig_go_5, bool _swig_go_6) {
  void *arg1 = (void *) 0 ;
  bool arg2 ;
  char *arg3 = (char *) 0 ;
  bool arg4 ;
  bool arg5 ;
  bool arg6 ;
  bool arg7 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (bool)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  arg6 = (bool)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  
  result = (void *)mountCheckbox(arg1,arg2,(char const *)arg3,arg4,arg5,arg6,arg7);
  *(void **)&_swig_go_result = (void *)result; 
  free(arg3); 
  return _swig_go_result;
}


void _wrap_checkboxUpdate_gtk_0b05487f82a429b0(void *_swig_go_0, bool _swig_go_1, _gostring_ _swig_go_2, bool _swig_go_3, bool _swig_go_4, bool _swig_go_5, bool _swig_go_6) {
  void *arg1 = (void *) 0 ;
  bool arg2 ;
  char *arg3 = (char *) 0 ;
  bool arg4 ;
  bool arg5 ;
  bool arg6 ;
  bool arg7 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (bool)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  arg6 = (bool)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  
  checkboxUpdate(arg1,arg2,(char const *)arg3,arg4,arg5,arg6,arg7);
  
  free(arg3); 
}


void _wrap_checkboxClick_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  checkboxClick(arg1);
  
}


bool _wrap_checkboxValue_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (bool)checkboxValue(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void *_wrap_mountTextbox_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, bool _swig_go_3, bool _swig_go_4, bool _swig_go_5, bool _swig_go_6, bool _swig_go_7, bool _swig_go_8, bool _swig_go_9) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  bool arg4 ;
  bool arg5 ;
  bool arg6 ;
  bool arg7 ;
  bool arg8 ;
  bool arg9 ;
  bool arg10 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (bool)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  arg6 = (bool)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  arg8 = (bool)_swig_go_7; 
  arg9 = (bool)_swig_go_8; 
  arg10 = (bool)_swig_go_9; 
  
  result = (void *)mountTextbox(arg1,(char const *)arg2,(char const *)arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
  *(void **)&_swig_go_result = (void *)result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


void _wrap_textboxUpdate_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, bool _swig_go_3, bool _swig_go_4, bool _swig_go_5, bool _swig_go_6, bool _swig_go_7, bool _swig_go_8, bool _swig_go_9) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  bool arg4 ;
  bool arg5 ;
  bool arg6 ;
  bool arg7 ;
  bool arg8 ;
  bool arg9 ;
  bool arg10 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (bool)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  arg6 = (bool)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  arg8 = (bool)_swig_go_7; 
  arg9 = (bool)_swig_go_8; 
  arg10 = (bool)_swig_go_9; 
  
  textboxUpdate(arg1,(char const *)arg2,(char const *)arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
  
  free(arg2); 
  free(arg3); 
}


_gostring_ _wrap_textboxText_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (char *)textboxText(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_ _wrap_textboxPlaceholder_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (char *)textboxPlaceholder(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


bool _wrap_textboxPassword_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (bool)textboxPassword(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_textboxReadOnly_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (bool)textboxReadOnly(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void *_wrap_mountTextarea_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1, bool _swig_go_2, bool _swig_go_3, bool _swig_go_4, bool _swig_go_5, bool _swig_go_6) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  bool arg4 ;
  bool arg5 ;
  bool arg6 ;
  bool arg7 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (bool)_swig_go_2; 
  arg4 = (bool)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  arg6 = (bool)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  
  result = (void *)mountTextarea(arg1,(char const *)arg2,arg3,arg4,arg5,arg6,arg7);
  *(void **)&_swig_go_result = (void *)result; 
  free(arg2); 
  return _swig_go_result;
}


void _wrap_textareaUpdate_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1, bool _swig_go_2, bool _swig_go_3, bool _swig_go_4, bool _swig_go_5, bool _swig_go_6) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  bool arg4 ;
  bool arg5 ;
  bool arg6 ;
  bool arg7 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (bool)_swig_go_2; 
  arg4 = (bool)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  arg6 = (bool)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  
  textareaUpdate(arg1,(char const *)arg2,arg3,arg4,arg5,arg6,arg7);
  
  free(arg2); 
}


_gostring_ _wrap_textareaText_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (char *)textareaText(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  free(result);
  return _swig_go_result;
}


_gostring_ _wrap_textareaPlaceholder_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (char *)textareaPlaceholder(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


bool _wrap_textareaReadOnly_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (bool)textareaReadOnly(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void *_wrap_textareaTextview_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (void *)textareaTextview(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void *_wrap_mountParagraph_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1, char _swig_go_2) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  char arg3 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (char)_swig_go_2; 
  
  result = (void *)mountParagraph(arg1,(char const *)arg2,arg3);
  *(void **)&_swig_go_result = (void *)result; 
  free(arg2); 
  return _swig_go_result;
}


void _wrap_paragraphUpdate_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1, char _swig_go_2) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  char arg3 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (char)_swig_go_2; 
  
  paragraphUpdate(arg1,(char const *)arg2,arg3);
  
  free(arg2); 
}


_gostring_ _wrap_paragraphText_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (char *)paragraphText(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


char _wrap_paragraphAlign_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  char result;
  char _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (char)paragraphAlign(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_paragraphSetText_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  paragraphSetText(arg1,(char const *)arg2);
  
  free(arg2); 
}


void *_wrap_mountProgressbar_gtk_0b05487f82a429b0(void *_swig_go_0, double _swig_go_1) {
  void *arg1 = (void *) 0 ;
  double arg2 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  result = (void *)mountProgressbar(arg1,arg2);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_progressbarUpdate_gtk_0b05487f82a429b0(void *_swig_go_0, double _swig_go_1) {
  void *arg1 = (void *) 0 ;
  double arg2 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  progressbarUpdate(arg1,arg2);
  
}


double _wrap_progressbarValue_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (double)progressbarValue(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void *_wrap_mountSlider_gtk_0b05487f82a429b0(void *_swig_go_0, double _swig_go_1, bool _swig_go_2, double _swig_go_3, double _swig_go_4, bool _swig_go_5, bool _swig_go_6, bool _swig_go_7) {
  void *arg1 = (void *) 0 ;
  double arg2 ;
  bool arg3 ;
  double arg4 ;
  double arg5 ;
  bool arg6 ;
  bool arg7 ;
  bool arg8 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  arg3 = (bool)_swig_go_2; 
  arg4 = (double)_swig_go_3; 
  arg5 = (double)_swig_go_4; 
  arg6 = (bool)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  arg8 = (bool)_swig_go_7; 
  
  result = (void *)mountSlider(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_sliderUpdate_gtk_0b05487f82a429b0(void *_swig_go_0, double _swig_go_1, bool _swig_go_2, double _swig_go_3, double _swig_go_4, bool _swig_go_5, bool _swig_go_6, bool _swig_go_7) {
  void *arg1 = (void *) 0 ;
  double arg2 ;
  bool arg3 ;
  double arg4 ;
  double arg5 ;
  bool arg6 ;
  bool arg7 ;
  bool arg8 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  arg3 = (bool)_swig_go_2; 
  arg4 = (double)_swig_go_3; 
  arg5 = (double)_swig_go_4; 
  arg6 = (bool)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  arg8 = (bool)_swig_go_7; 
  
  sliderUpdate(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  
}


double _wrap_sliderValue_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (double)sliderValue(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void *_wrap_mountHR_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (void *)mountHR(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void *_wrap_mountImage_gtk_0b05487f82a429b0(void *_swig_go_0, char *_swig_go_1, intgo _swig_go_2, intgo _swig_go_3, intgo _swig_go_4) {
  void *arg1 = (void *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = *(unsigned char **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = (int)_swig_go_4; 
  
  result = (void *)mountImage(arg1,(unsigned char const *)arg2,arg3,arg4,arg5);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void *_wrap_imageUpdate_gtk_0b05487f82a429b0(void *_swig_go_0, char *_swig_go_1, intgo _swig_go_2, intgo _swig_go_3, intgo _swig_go_4) {
  void *arg1 = (void *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = *(unsigned char **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = (int)_swig_go_4; 
  
  result = (void *)imageUpdate(arg1,(unsigned char const *)arg2,arg3,arg4,arg5);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_imageColorSpace_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (unsigned int)imageColorSpace(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_imageHasAlpha_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (bool)imageHasAlpha(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_imageImageWidth_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (unsigned int)imageImageWidth(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_imageImageHeight_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (unsigned int)imageImageHeight(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_imageImageStride_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (unsigned int)imageImageStride(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void *_wrap_mountDecoration_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3) {
  void *arg1 = (void *) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  int arg4 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  arg3 = (unsigned int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  
  result = (void *)mountDecoration(arg1,arg2,arg3,arg4);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_decorationUpdate_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3) {
  void *arg1 = (void *) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  int arg4 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  arg3 = (unsigned int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  
  decorationUpdate(arg1,arg2,arg3,arg4);
  
}


intgo _wrap_decorationFill_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (unsigned int)decorationFill(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_decorationStroke_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (unsigned int)decorationStroke(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_decorationRadius_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (int)decorationRadius(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_decorationSetRadius_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  decorationSetRadius(arg1,arg2);
  
}


void *_wrap_mountCombobox_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1, intgo _swig_go_2, bool _swig_go_3, bool _swig_go_4, bool _swig_go_5, bool _swig_go_6, bool _swig_go_7) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  bool arg4 ;
  bool arg5 ;
  bool arg6 ;
  bool arg7 ;
  bool arg8 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (int)_swig_go_2; 
  arg4 = (bool)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  arg6 = (bool)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  arg8 = (bool)_swig_go_7; 
  
  result = (void *)mountCombobox(arg1,(char const *)arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  *(void **)&_swig_go_result = (void *)result; 
  free(arg2); 
  return _swig_go_result;
}


void _wrap_comboboxUpdate_gtk_0b05487f82a429b0(void *_swig_go_0, _gostring_ _swig_go_1, intgo _swig_go_2, bool _swig_go_3, bool _swig_go_4, bool _swig_go_5, bool _swig_go_6, bool _swig_go_7) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  bool arg4 ;
  bool arg5 ;
  bool arg6 ;
  bool arg7 ;
  bool arg8 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (int)_swig_go_2; 
  arg4 = (bool)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  arg6 = (bool)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  arg8 = (bool)_swig_go_7; 
  
  comboboxUpdate(arg1,(char const *)arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  
  free(arg2); 
}


void *_wrap_comboboxChild_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (void *)comboboxChild(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_comboboxItemCount_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (unsigned int)comboboxItemCount(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


_gostring_ _wrap_comboboxItem_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1) {
  void *arg1 = (void *) 0 ;
  unsigned int arg2 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  
  result = (char *)comboboxItem(arg1,arg2);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_comboboxValue_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (int)comboboxValue(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void *_wrap_mountTabs_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2, bool _swig_go_3) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  bool arg4 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (bool)_swig_go_3; 
  
  result = (void *)mountTabs(arg1,arg2,arg3,arg4);
  *(void **)&_swig_go_result = (void *)result; 
  free(arg3); 
  return _swig_go_result;
}


void _wrap_tabsUpdate_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2, bool _swig_go_3) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  bool arg4 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (bool)_swig_go_3; 
  
  tabsUpdate(arg1,arg2,arg3,arg4);
  
  free(arg3); 
}


void *_wrap_tabsGetTabParent_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (void *)tabsGetTabParent(arg1,arg2);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_tabsItemCount_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (int)tabsItemCount(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


_gostring_ _wrap_tabsItemCaption_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (char *)tabsItemCaption(arg1,arg2);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void *_wrap_mountIntInput_gtk_0b05487f82a429b0(void *_swig_go_0, long long _swig_go_1, _gostring_ _swig_go_2, bool _swig_go_3, long long _swig_go_4, long long _swig_go_5, bool _swig_go_6, bool _swig_go_7, bool _swig_go_8, bool _swig_go_9) {
  void *arg1 = (void *) 0 ;
  long arg2 ;
  char *arg3 = (char *) 0 ;
  bool arg4 ;
  long arg5 ;
  long arg6 ;
  bool arg7 ;
  bool arg8 ;
  bool arg9 ;
  bool arg10 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (long)_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (bool)_swig_go_3; 
  arg5 = (long)_swig_go_4; 
  arg6 = (long)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  arg8 = (bool)_swig_go_7; 
  arg9 = (bool)_swig_go_8; 
  arg10 = (bool)_swig_go_9; 
  
  result = (void *)mountIntInput(arg1,arg2,(char const *)arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
  *(void **)&_swig_go_result = (void *)result; 
  free(arg3); 
  return _swig_go_result;
}


void _wrap_intinputUpdate_gtk_0b05487f82a429b0(void *_swig_go_0, long long _swig_go_1, _gostring_ _swig_go_2, bool _swig_go_3, long long _swig_go_4, long long _swig_go_5, bool _swig_go_6, bool _swig_go_7, bool _swig_go_8, bool _swig_go_9) {
  void *arg1 = (void *) 0 ;
  long arg2 ;
  char *arg3 = (char *) 0 ;
  bool arg4 ;
  long arg5 ;
  long arg6 ;
  bool arg7 ;
  bool arg8 ;
  bool arg9 ;
  bool arg10 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (long)_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (bool)_swig_go_3; 
  arg5 = (long)_swig_go_4; 
  arg6 = (long)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  arg8 = (bool)_swig_go_7; 
  arg9 = (bool)_swig_go_8; 
  arg10 = (bool)_swig_go_9; 
  
  intinputUpdate(arg1,arg2,(char const *)arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
  
  free(arg3); 
}


long long _wrap_intinputValue_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  long result;
  long long _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (long)intinputValue(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_intinputMin_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (double)intinputMin(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_intinputMax_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (double)intinputMax(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void *_wrap_mountDateInput_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, bool _swig_go_4, bool _swig_go_5, bool _swig_go_6, bool _swig_go_7) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  unsigned int arg3 ;
  unsigned int arg4 ;
  bool arg5 ;
  bool arg6 ;
  bool arg7 ;
  bool arg8 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (unsigned int)_swig_go_2; 
  arg4 = (unsigned int)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  arg6 = (bool)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  arg8 = (bool)_swig_go_7; 
  
  result = (void *)mountDateInput(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_dateInputUpdate_gtk_0b05487f82a429b0(void *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, bool _swig_go_4, bool _swig_go_5, bool _swig_go_6, bool _swig_go_7) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  unsigned int arg3 ;
  unsigned int arg4 ;
  bool arg5 ;
  bool arg6 ;
  bool arg7 ;
  bool arg8 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (unsigned int)_swig_go_2; 
  arg4 = (unsigned int)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  arg6 = (bool)_swig_go_5; 
  arg7 = (bool)_swig_go_6; 
  arg8 = (bool)_swig_go_7; 
  
  dateInputUpdate(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  
}


intgo _wrap_dateInputYear_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (int)dateInputYear(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_dateInputMonth_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (unsigned int)dateInputMonth(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_dateInputDay_gtk_0b05487f82a429b0(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  result = (unsigned int)dateInputDay(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

