// Crypt deals with Fernet encryption and decryption using PBK2DF
package clipster

import (
	"crypto/sha256"
	"encoding/base64"
	"log"

	"github.com/fernet/fernet-go"
	"golang.org/x/crypto/pbkdf2"
)

func deriveKey(user string, pw string, iters int) string {
	// deriveKey from password using a salt via PBK2DF and return urlsafe b64
	// cross client compatible by using same parameters and same algos
	salt := "clipster_" + user + "_" + pw
	key := pbkdf2.Key([]byte(pw), []byte(salt), iters, HASH_LENGTH, sha256.New)
	key_b64 := base64.URLEncoding.EncodeToString(key)
	log.Println("Ok: derived key string b64", key_b64)
	return key_b64
}

func Encrypt(user string, pw string, text string, iters int) string {
	// Encrypt the password using Fernet and a key generated by deriveKey()
	key_b64 := deriveKey(user, pw, iters)
	key := fernet.MustDecodeKeys(key_b64)
	tok, err := fernet.EncryptAndSign([]byte(text), key[0])
	if err != nil {
		log.Fatalln("Error:", err)
	}
	log.Println("Ok: encrypted token string", string(tok))
	return string(tok)
}

func GetLoginHashFromPw(user string, pw string) string {
	// PwToHash returns a hash of the password for login
	hash := deriveKey(user, pw, HASH_ITERS_LOGIN)
	return hash
}

func GetMsgHashFromPw(user string, pw string) string {
	// GetPwHash returns password hash as strings
	hash := deriveKey(user, pw, HASH_ITERS_MSG)
	return hash
}
